import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-providers";

const workSans = localFont({
   src: "./fonts/WorkSans-VariableFont_wght.ttf"
});


export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="es">
         <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
         </head>
         <body
            className={`${workSans.className} antialiased overflow-hidden`}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               {children}
            </ThemeProvider>
         </body>

      </html>
   );
}
