import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-providers";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const workSans = localFont({
   src: "./fonts/WorkSans-VariableFont_wght.ttf"
});


export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="es">
         <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
         </head>
         <body
            className={`${workSans.className} antialiased overflow-hidden`}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               <Navbar />
               <main className="relative h-screen overflow-auto ">
                  <div className="px-4 container mx-auto lg:px-0">
                     <div className="h-[60px]" />
                     {children}
                     <div className="h-[60px]" />
                  </div>
               </main>
               <Footer />
            </ThemeProvider>
         </body>

      </html>
   );
}
